check GitVersion to detect gke and eks clusters and activate node-agent
kubescape/helm-charts pull request #194
Opened 2023-06-12 14:54 UTC by matthyx

## Overview

2023-06-12 15:02 UTC, amirmalka approved these changes

2023-06-15 08:03 UTC, dwertent commented
@matthyx What if I'm running an unmanaged cluster but I still want relevancy to run. How can I do that?

2023-06-15 08:06 UTC, matthyx commented
> @matthyx What if I'm running an unmanaged cluster but I still want relevancy to run. How can I do that?

you can't... should I add a forceEnable to relevancy?

2023-06-15 08:54 UTC, dwertent commented
Great!
We will merge this after we see the system tests are stable. Because we will need the system tests to run 
```
--set capabilities.relevancy=enable
```
instead of enabling the `node-agent`.

2023-06-15 08:55 UTC, matthyx commented
> Great! We will merge this after we see the system tests are stable. Because we will need the system tests to run
> 
> ```
> --set capabilities.relevancy=enable
> ```
> 
> instead of enabling the `node-agent`.

works on my PC btw 😅

2023-06-15 13:04 UTC, dwertent requested changes

2023-06-15 13:04 UTC, dwertent commented on charts/kubescape-cloud-operator/values.yaml
> +  relevancy: detect # enable/disable/detect
Default should be `disable`

2023-06-15 14:01 UTC, merged