add rbac for application profile CRDs
kubescape/helm-charts pull request #284
Opened 2023-09-15 15:18 UTC by matthyx

## PR Type:
Enhancement

___
## PR Description:
This PR enhances the Role-Based Access Control (RBAC) for application profile CRDs by adding new resources to the cluster role. It also introduces a new configuration for enabling the application profile service. Additionally, the PR updates the image repositories and tags for the storage and node-agent services to use a different source.

___
## PR Main Files Walkthrough:
`charts/kubescape-operator/templates/_helpers.tpl`: Added a new helper for runtime observability configuration.
`charts/kubescape-cloud-operator/README.md`: Removed the content of the README file, indicating the deprecation of the Kubescape Operator.
`charts/kubescape-operator/templates/node-agent/clusterrole.yaml`: Added new resources ("applicationactivities", "applicationprofiles", "applicationprofilesummaries") to the cluster role for the node-agent.
`charts/kubescape-operator/templates/node-agent/configmap.yaml`: Added a new configuration for enabling the application profile service in the node-agent's configmap.
`charts/kubescape-operator/values.yaml`: Updated the image repositories and tags for the storage and node-agent services. Also, added a new configuration for runtime observability.

2023-09-19 11:51 UTC, dwertent requested changes

2023-09-19 11:51 UTC, dwertent commented on charts/kubescape-operator/values.yaml
> +    repository: quay.io/matthiasb_1/storage
Please use the kubescape org

2023-09-19 11:52 UTC, matthyx commented on charts/kubescape-operator/values.yaml
> +    repository: quay.io/matthiasb_1/storage
yes, I'll update the node-agent too

2023-10-12 08:28 UTC, dwertent commented
@matthyx can we merge this? what is the status?

2023-10-12 08:30 UTC, matthyx commented
> @matthyx can we merge this? what is the status?

yes, it just adds some rbac along with the image bumps for application profile

2023-10-12 08:39 UTC, dwertent approved these changes

2023-10-12 08:40 UTC, merged