Adding Prometheus Exporter to Helm Charts
kubescape/helm-charts pull request #343
Opened 2023-12-07 15:05 UTC by 0xt3j4s

## Overview

- This PR will add the prometheus exporter to the helm charts.

2023-12-10 15:01 UTC, dwertent requested changes
Well done!
Please see my few comments.

In addition, we should add documentation and we should remove the deprecated Prometheus support (currently we support only the kubescape workload).

2023-12-10 15:02 UTC, dwertent commented
@0xt3j4s What are the metrics that will be supported? Configuration scanning and image scanning?

2023-12-11 10:56 UTC, matthyx commented on charts/kubescape-operator/values.yaml
> +  resources:
no for sure, also we must debug the exporter that's crashing

2023-12-11 15:36 UTC, 0xt3j4s commented
Currently, the metrics support configuration scanning (control metrics) and image scanning (vulnerability metrics).

2023-12-11 15:39 UTC, 0xt3j4s commented on charts/kubescape-operator/values.yaml
> +  resources:
Yes, there is some issue with the docker image (keeps crashing).

2023-12-14 11:40 UTC, dwertent commented
@0xt3j4s Can you pls fix the conflicts?

2023-12-21 07:31 UTC, dwertent commented on charts/kubescape-operator/values.yaml
> +  resources:
@0xt3j4s Was this issue solved?

2023-12-21 12:53 UTC, dwertent commented on charts/kubescape-operator/templates/prometheus-exporter/deployment.yaml
> +
Please add `customScheduling` as introduced [here](https://github.com/kubescape/helm-charts/pull/359/files#diff-a6c71225bcec775a304738cdcfc01ac0feb870555f0fa2297b0aaca4bc62cdd6R56)

2023-12-21 13:18 UTC, 0xt3j4s commented on charts/kubescape-operator/values.yaml
> +  resources:
Not yet; I will have to check with @matthyx once.

2023-12-28 23:03 UTC, matthyx commented on charts/kubescape-operator/values.yaml
> +  resources:
image fixed (using my own quay until we merge https://github.com/kubescape/prometheus-exporter/pull/6)

2024-01-11 23:32 UTC, merged