wip: Ignore account id if secret exists
kubescape/helm-charts pull request #349
Opened 2023-12-12 09:54 UTC by dwertent

## Overview

2023-12-12 10:23 UTC, matthyx requested changes

2023-12-12 10:23 UTC, matthyx commented on charts/kubescape-operator/templates/kubescape/clusterrole.yaml
> +  resources: ["csistoragecapacities", "storageclasses"]
StorageClass (I think the capitalization is important)

2023-12-14 11:41 UTC, dwertent commented on charts/kubescape-operator/templates/kubescape/clusterrole.yaml
> +  resources: ["csistoragecapacities", "storageclasses"]
```suggestion
  resources: ["csistoragecapacities", "StorageClass"]
```

2023-12-14 12:03 UTC, matthyx approved these changes

2023-12-14 18:43 UTC, merged