prepare next release
kubescape/helm-charts pull request #438
Opened 2024-05-15 19:51 UTC by matthyx

2024-05-15 19:52 UTC, slashben approved these changes
I am looking only at the KDR part. It looks OK!

2024-05-21 05:50 UTC, dwertent commented on charts/kubescape-operator/values.yaml
> +    tag: 1.2.0-6_base
```suggestion
    tag: v1.2.0
```

2024-05-21 05:50 UTC, dwertent commented on charts/kubescape-operator/values.yaml
> +    repository: quay.io/kubescape/klamav
`klamav` seriously? 🤓

2024-05-27 15:56 UTC, dwertent requested changes

2024-05-27 15:56 UTC, dwertent commented on charts/kubescape-operator/values.yaml
> +  runtimeDetection: enable
```suggestion
  runtimeDetection: disable
```

2024-05-27 15:56 UTC, dwertent commented on charts/kubescape-operator/values.yaml
> +  malwareDetection: enable
```suggestion
  malwareDetection: disable
```

2024-05-27 15:56 UTC, dwertent commented on charts/kubescape-operator/values.yaml
> +  installDefault: true # install the default CRD
```suggestion
  installDefault: false # install the default CRD
```

2024-05-27 15:56 UTC, dwertent commented on charts/kubescape-operator/values.yaml
> +  scopeClustered: true # it is better to have the CRDs in the cluster scope
```suggestion
  scopeClustered: false # it is better to have the CRDs in the cluster scope
```

2024-05-27 16:06 UTC, dwertent approved these changes

2024-05-27 16:07 UTC, merged