namespace updated to kubescape(default) for kubescape-host-scanner ds
kubescape/helm-charts pull request #63
Opened 2023-02-07 18:37 UTC by nikhilbagdi

## Overview

Removed the manifest to create namespace from file ```charts/kubescape-cloud-operator/assets/host-scanner-definition.yaml``` and updated the manifest of ```kubescape-host-scanner``` DaemonSet for namespace.

## How to Test

Deploy the ```kubescape-cloud-operator```.
 
## Related issues/PRs:

* Resolved #61 

## Checklist before requesting a review

- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [x] New and existing unit tests pass locally with my changes

2023-02-08 06:31 UTC, Bezbran requested changes

2023-02-08 06:31 UTC, Bezbran commented on charts/kubescape-cloud-operator/assets/host-scanner-definition.yaml
> +  namespace: {{ .Values.ksNamespace }}
We need forst to upadte kubescape code so it won't delete the host-scanner namespace once it finished.

2023-02-08 06:31 UTC, Bezbran commented on charts/kubescape-cloud-operator/assets/host-scanner-definition.yaml
> +  namespace: {{ .Values.ksNamespace }}
https://github.com/kubescape/kubescape/blob/2a0a2cf95ab59a54ab190179bb33f837a02447bc/core/pkg/hostsensorutils/hostsensordeploy.go#L279

2023-02-08 06:31 UTC, Bezbran commented on charts/kubescape-cloud-operator/assets/host-scanner-definition.yaml
> +  namespace: {{ .Values.ksNamespace }}
And we need to fix the YAML in kubescape itself as well:
https://github.com/kubescape/kubescape/blob/master/core/pkg/hostsensorutils/hostsensor.yaml

2023-05-30 07:09 UTC, dwertent commented
Merged in #149

2023-05-30 07:09 UTC, closed without merging